on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # weekly on Sunday
  workflow_dispatch:

jobs:
  scorecards:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read  
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2.3.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          results_file: scorecards-results.json
          results_format: json
